name: Ubuntu Server via Browser (Flask + ngrok)

on:
  workflow_dispatch:
  push:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip curl jq
          pip3 install flask

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xzf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok

      - name: Auth ngrok
        run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Flask server
        env:
          LOGIN_SEC: ${{ secrets.LOGIN_SEC }}
          SENHA_SEC: ${{ secrets.SENHA_SEC }}
        run: |
          nohup python3 app.py > flask.log 2>&1 &
          sleep 3
          curl http://127.0.0.1:5000

      - name: Start ngrok HTTP
        run: |
          ./ngrok http 127.0.0.1:5000 &
          sleep 5
          echo "URL PÚBLICA:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep server alive (6 hours)
        run: |
          echo "Servidor ativo por até 6 horas..."
          sleep 21600
