name: ShellInABox + ngrok

on:
  workflow_dispatch:
  push:

jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t shellinabox .

      - name: Run container
        run: |
          docker run -d \
            --name shellinabox \
            -p 4200:4200 \
            -e LOGIN_SEC=${{ secrets.LOGIN_SEC }} \
            -e SENHA_SEC=${{ secrets.SENHA_SEC }} \
            shellinabox


      - name: Install ngrok
        run: |
          curl -fsSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc |
          sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com jammy main" |
          sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok jq

      - name: Auth ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start ngrok
        run: |
          ngrok http 4200 &
          sleep 5
          echo "TERMINAL WEB:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep alive
        run: sleep 21600
