name: ShellInABox via Browser + ngrok

on:
  workflow_dispatch:
  push:

jobs:
  shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ShellInABox image
        run: docker build -t shellinabox .

      - name: Run ShellInABox container
        run: |
          docker run -d \
            --name shellinabox \
            -p 4200:4200 \
            -e LOGIN_SEC=${{ secrets.LOGIN_SEC }} \
            -e SENHA_SEC=${{ secrets.SENHA_SEC }} \
            shellinabox

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xzf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok

      - name: Auth ngrok
        run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok
        run: |
          ./ngrok http 4200 &
          sleep 5
          echo "URL PÃšBLICA:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Keep job alive
        run: |
          echo "ShellInABox protegido por login/senha"
          while true; do sleep 60; done
